// ============================================================
// Niggir · ንግግር — Amharic learning data
// Vocabulary curated to standard Amharic dictionary orthography
// (Ge'ez script forms as found in Kane's Amharic–English
// Dictionary and standard references). Edit freely to extend.
// Each word: am = Amharic (fidel), tr = transliteration, en = English.
// ============================================================

// The 7 vowel orders of the fidel syllabary
const VOWEL_ORDERS = ["ä", "u", "i", "a", "e", "ə", "o"];

// Base consonant families. base = Unicode codepoint of 1st order.
// sound = romanized consonant used in quizzes. Families marked with
// note share a modern pronunciation with another letter.
const FIDEL_FAMILIES = [
  { base: 0x1200, sound: "h",   note: "" },
  { base: 0x1208, sound: "l",   note: "" },
  { base: 0x1210, sound: "h",   note: "same sound as ሀ in modern Amharic" },
  { base: 0x1218, sound: "m",   note: "" },
  { base: 0x1220, sound: "s",   note: "same sound as ሰ in modern Amharic" },
  { base: 0x1228, sound: "r",   note: "" },
  { base: 0x1230, sound: "s",   note: "" },
  { base: 0x1238, sound: "sh",  note: "" },
  { base: 0x1240, sound: "q",   note: "ejective k" },
  { base: 0x1260, sound: "b",   note: "" },
  { base: 0x1268, sound: "v",   note: "used in loanwords" },
  { base: 0x1270, sound: "t",   note: "" },
  { base: 0x1278, sound: "ch",  note: "" },
  { base: 0x1280, sound: "h",   note: "same sound as ሀ in modern Amharic" },
  { base: 0x1290, sound: "n",   note: "" },
  { base: 0x1298, sound: "ny",  note: "like Spanish ñ" },
  { base: 0x12A0, sound: "a",   note: "glottal vowel carrier" },
  { base: 0x12A8, sound: "k",   note: "" },
  { base: 0x12B8, sound: "h",   note: "same sound as ሀ in modern Amharic" },
  { base: 0x12C8, sound: "w",   note: "" },
  { base: 0x12D0, sound: "a",   note: "same use as አ in modern Amharic" },
  { base: 0x12D8, sound: "z",   note: "" },
  { base: 0x12E0, sound: "zh",  note: "like s in 'measure'" },
  { base: 0x12E8, sound: "y",   note: "" },
  { base: 0x12F0, sound: "d",   note: "" },
  { base: 0x1300, sound: "j",   note: "" },
  { base: 0x1308, sound: "g",   note: "" },
  { base: 0x1320, sound: "t'",  note: "ejective t" },
  { base: 0x1328, sound: "ch'", note: "ejective ch" },
  { base: 0x1330, sound: "p'",  note: "ejective p" },
  { base: 0x1338, sound: "ts'", note: "ejective ts" },
  { base: 0x1340, sound: "ts'", note: "same sound as ጸ in modern Amharic" },
  { base: 0x1348, sound: "f",   note: "" },
  { base: 0x1350, sound: "p",   note: "used in loanwords" },
];

const LESSONS = [
  { id: "f1", type: "fidel", emoji: "ሀ", title: "Fidel I", desc: "ሀ – ሸ · the first letters", fams: [0,1,2,3,4,5,6,7] },
  { id: "greetings", type: "vocab", emoji: "👋", title: "Greetings", desc: "Say hello like a local", words: [
    { am: "ሰላም", tr: "selam", en: "hello / peace" },
    { am: "እንደምን ነህ?", tr: "endemin neh?", en: "how are you? (to a man)" },
    { am: "እንደምን ነሽ?", tr: "endemin nesh?", en: "how are you? (to a woman)" },
    { am: "ደህና ነኝ", tr: "dehna negn", en: "I am fine" },
    { am: "አመሰግናለሁ", tr: "ameseginalehu", en: "thank you" },
    { am: "እባክህ", tr: "ebakih", en: "please (to a man)" },
    { am: "አዎ", tr: "awo", en: "yes" },
    { am: "አይደለም", tr: "aydelem", en: "no / it is not" },
    { am: "ይቅርታ", tr: "yiqirta", en: "sorry / excuse me" },
    { am: "ደህና ሁን", tr: "dehna hun", en: "goodbye (to a man)" },
  ]},
  { id: "numbers", type: "vocab", emoji: "🔢", title: "Numbers", desc: "Count from 1 to 10", words: [
    { am: "አንድ", tr: "and", en: "one" },
    { am: "ሁለት", tr: "hulet", en: "two" },
    { am: "ሶስት", tr: "sost", en: "three" },
    { am: "አራት", tr: "arat", en: "four" },
    { am: "አምስት", tr: "amist", en: "five" },
    { am: "ስድስት", tr: "sidist", en: "six" },
    { am: "ሰባት", tr: "sebat", en: "seven" },
    { am: "ስምንት", tr: "simint", en: "eight" },
    { am: "ዘጠኝ", tr: "zetegn", en: "nine" },
    { am: "አስር", tr: "asir", en: "ten" },
  ]},
  { id: "f2", type: "fidel", emoji: "ቀ", title: "Fidel II", desc: "ቀ – ኘ · more letters", fams: [8,9,10,11,12,13,14,15] },
  { id: "family", type: "vocab", emoji: "👨‍👩‍👧", title: "Family", desc: "The people closest to you", words: [
    { am: "እናት", tr: "enat", en: "mother" },
    { am: "አባት", tr: "abat", en: "father" },
    { am: "ወንድም", tr: "wendim", en: "brother" },
    { am: "እህት", tr: "ehit", en: "sister" },
    { am: "ልጅ", tr: "lij", en: "child" },
    { am: "ሴት", tr: "set", en: "woman" },
    { am: "ወንድ", tr: "wend", en: "man" },
    { am: "አያት", tr: "ayat", en: "grandparent" },
    { am: "ባል", tr: "bal", en: "husband" },
    { am: "ሚስት", tr: "mist", en: "wife" },
  ]},
  { id: "food", type: "vocab", emoji: "🍲", title: "Food & Drink", desc: "From buna to injera", words: [
    { am: "ውሃ", tr: "wiha", en: "water" },
    { am: "ዳቦ", tr: "dabo", en: "bread" },
    { am: "ቡና", tr: "buna", en: "coffee" },
    { am: "ሻይ", tr: "shai", en: "tea" },
    { am: "ወተት", tr: "wetet", en: "milk" },
    { am: "እንጀራ", tr: "injera", en: "injera (flatbread)" },
    { am: "ስጋ", tr: "siga", en: "meat" },
    { am: "አትክልት", tr: "atkilt", en: "vegetables" },
    { am: "ፍራፍሬ", tr: "firafre", en: "fruit" },
    { am: "ምግብ", tr: "migib", en: "food" },
  ]},
  { id: "f3", type: "fidel", emoji: "አ", title: "Fidel III", desc: "አ – ጀ · keep going", fams: [16,17,18,19,20,21,22,23,24,25] },
  { id: "verbs", type: "vocab", emoji: "🏃", title: "Common Verbs", desc: "Words that do things", words: [
    { am: "መብላት", tr: "meblat", en: "to eat" },
    { am: "መጠጣት", tr: "metetat", en: "to drink" },
    { am: "መሄድ", tr: "mehed", en: "to go" },
    { am: "መምጣት", tr: "memtat", en: "to come" },
    { am: "ማየት", tr: "mayet", en: "to see" },
    { am: "መስማት", tr: "mesmat", en: "to hear" },
    { am: "መናገር", tr: "menager", en: "to speak" },
    { am: "መስራት", tr: "mesrat", en: "to work" },
    { am: "መተኛት", tr: "metegnat", en: "to sleep" },
    { am: "መውደድ", tr: "mewded", en: "to love / like" },
  ]},
  { id: "objects", type: "vocab", emoji: "🏠", title: "Everyday Things", desc: "Objects around you", words: [
    { am: "ቤት", tr: "bet", en: "house" },
    { am: "መኪና", tr: "mekina", en: "car" },
    { am: "መጽሐፍ", tr: "metsihaf", en: "book" },
    { am: "ስልክ", tr: "silk", en: "phone" },
    { am: "ጠረጴዛ", tr: "terepieza", en: "table" },
    { am: "ወንበር", tr: "wenber", en: "chair" },
    { am: "በር", tr: "ber", en: "door" },
    { am: "መስኮት", tr: "meskot", en: "window" },
    { am: "ገንዘብ", tr: "genzeb", en: "money" },
    { am: "ልብስ", tr: "libs", en: "clothes" },
  ]},
  { id: "f4", type: "fidel", emoji: "ገ", title: "Fidel IV", desc: "ገ – ፐ · the final letters", fams: [26,27,28,29,30,31,32,33] },
  { id: "time", type: "vocab", emoji: "🕐", title: "Time", desc: "Days, nights and seasons", words: [
    { am: "ቀን", tr: "qen", en: "day" },
    { am: "ሌሊት", tr: "lelit", en: "night" },
    { am: "ጠዋት", tr: "tewat", en: "morning" },
    { am: "ማታ", tr: "mata", en: "evening" },
    { am: "ዛሬ", tr: "zare", en: "today" },
    { am: "ነገ", tr: "nege", en: "tomorrow" },
    { am: "ትናንት", tr: "tinant", en: "yesterday" },
    { am: "ሳምንት", tr: "samint", en: "week" },
    { am: "ወር", tr: "wer", en: "month" },
    { am: "ዓመት", tr: "amet", en: "year" },
  ]},
  { id: "colors", type: "vocab", emoji: "🎨", title: "Colors", desc: "Paint your words", words: [
    { am: "ቀይ", tr: "qey", en: "red" },
    { am: "አረንጓዴ", tr: "arenguade", en: "green" },
    { am: "ቢጫ", tr: "bicha", en: "yellow" },
    { am: "ጥቁር", tr: "tiqur", en: "black" },
    { am: "ነጭ", tr: "nech", en: "white" },
    { am: "ሰማያዊ", tr: "semayawi", en: "blue" },
    { am: "ቡናማ", tr: "bunama", en: "brown" },
    { am: "ግራጫ", tr: "giracha", en: "gray" },
    { am: "ብርቱካናማ", tr: "birtukanama", en: "orange (color)" },
  ]},
  { id: "body", type: "vocab", emoji: "💪", title: "The Body", desc: "Head to toe", words: [
    { am: "ራስ", tr: "ras", en: "head" },
    { am: "ዓይን", tr: "ayn", en: "eye" },
    { am: "ጆሮ", tr: "joro", en: "ear" },
    { am: "አፍ", tr: "af", en: "mouth" },
    { am: "አፍንጫ", tr: "afincha", en: "nose" },
    { am: "እጅ", tr: "ij", en: "hand" },
    { am: "እግር", tr: "igir", en: "foot / leg" },
    { am: "ልብ", tr: "lib", en: "heart" },
    { am: "ሆድ", tr: "hod", en: "stomach" },
    { am: "ጥርስ", tr: "tirs", en: "tooth" },
  ]},
  { id: "places", type: "vocab", emoji: "🏙️", title: "Places", desc: "Around the city", words: [
    { am: "ከተማ", tr: "ketema", en: "city" },
    { am: "ገበያ", tr: "gebeya", en: "market" },
    { am: "ትምህርት ቤት", tr: "timhirt bet", en: "school" },
    { am: "ሆስፒታል", tr: "hospital", en: "hospital" },
    { am: "ቤተ ክርስቲያን", tr: "bete kristiyan", en: "church" },
    { am: "መስጊድ", tr: "mesgid", en: "mosque" },
    { am: "ሆቴል", tr: "hotel", en: "hotel" },
    { am: "መንገድ", tr: "menged", en: "road / street" },
    { am: "ሀገር", tr: "hager", en: "country" },
    { am: "ባንክ", tr: "bank", en: "bank" },
  ]},
  { id: "adjectives", type: "vocab", emoji: "✨", title: "Describing", desc: "Big, small, beautiful", words: [
    { am: "ትልቅ", tr: "tiliq", en: "big" },
    { am: "ትንሽ", tr: "tinish", en: "small" },
    { am: "ጥሩ", tr: "tiru", en: "good" },
    { am: "መጥፎ", tr: "metfo", en: "bad" },
    { am: "ቆንጆ", tr: "qonjo", en: "beautiful" },
    { am: "አዲስ", tr: "addis", en: "new" },
    { am: "አሮጌ", tr: "aroge", en: "old (thing)" },
    { am: "ረጅም", tr: "rejim", en: "tall / long" },
    { am: "አጭር", tr: "achir", en: "short" },
    { am: "ፈጣን", tr: "fetan", en: "fast" },
  ]},
  { id: "phrases", type: "vocab", emoji: "💬", title: "Survival Phrases", desc: "Real conversations", words: [
    { am: "ስሜ ... ነው", tr: "sime ... new", en: "my name is ..." },
    { am: "ስምህ ማን ነው?", tr: "simih man new?", en: "what is your name? (to a man)" },
    { am: "ስንት ነው?", tr: "sint new?", en: "how much is it?" },
    { am: "የት ነው?", tr: "yet new?", en: "where is it?" },
    { am: "አልገባኝም", tr: "algebagnim", en: "I don't understand" },
    { am: "ራበኝ", tr: "rabegn", en: "I am hungry" },
    { am: "ጠማኝ", tr: "temagn", en: "I am thirsty" },
    { am: "እወድሃለሁ", tr: "ewedihalehu", en: "I love you (to a man)" },
    { am: "እወድሻለሁ", tr: "ewedishalehu", en: "I love you (to a woman)" },
    { am: "አማርኛ እየተማርኩ ነው", tr: "amarigna eyetemarku new", en: "I am learning Amharic" },
    { am: "በጣም", tr: "betam", en: "very / a lot" },
  ]},
];
